version: '3.3'
services:
  # ----- reverse-proxy --------------------------------------------------------
  traefik:
    image: "traefik:2.0"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "9080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # ----- autocomplete-transit -------------------------------------------------
  autocomplete-transit-elastic:
    image: elasticsearch:6.4.3
    environment:
      - discovery.type=single-node
    #ports:
      #- "9200:9200"
    volumes:
      - autocomplete-transit-elastic:/usr/share/elasticsearch/data

  autocomplete-transit-importer:
    build: ./nextmoov-smop-autocomplete-transit/importer
    depends_on:
      - autocomplete-transit-elastic
    volumes:
      - ./data:/app/tmp

  autocomplete-transit-api:
    build: ./nextmoov-smop-autocomplete-transit/api
    depends_on:
      - autocomplete-transit-elastic
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.routers.autocomplete-transit-api.entrypoints=web"
      - "traefik.http.routers.autocomplete-transit-api.rule=PathPrefix(`/autocomplete/station`)"
    #ports:
      #- "8082:80"

volumes:
  autocomplete-transit-elastic:
  
