version: '3'
services:
  elastic:
    image: elasticsearch:6.4.3
    #ports:
      #- "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  importer:
    build: importer
    depends_on:
      - elastic
    volumes:
      - ./tmp:/app/tmp

  api:
    build: api
    depends_on:
      - elastic
    ports:
      - "8083:80"

volumes:
  elastic:
